### PR TITLE
Style the competition window for top teams, Java 8

### PR DESCRIPTION
**Pull request by rootatkali**

### CODE REVIEW

**Comment by rootatkali** [comment]
@talbor49 Please review and merge

**Comment by talbor49** [comment]
LGTM, let's make sure with oded or danny that advancing to java 8 is OK (we need to update the guides on the website e.g)

**Review by talbor49 — APPROVED** [review]
LGTM, let's make sure with oded or danny that advancing to java 8 is OK (we need to update the guides on the website e.g)

**Comment by rootatkali** [comment]
I messaged Oded and Danny - the upgrade to Java 8 is approved. Merging.

**Pull request merged**
